import argparse

def parse_bash_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--d_model", type=int, default=512)
    parser.add_argument("--num_heads", type=int, default=8)
    parser.add_argument("--d_ff", type=int, default=1344)
    parser.add_argument("--vocab_size", type=int, default=32000)
    parser.add_argument("--num_layers", type=int, default=6)
    parser.add_argument("--max_seq_length", type=int, default=512)
    parser.add_argument("--seq_length", type=int, default=256)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--theta", type=int, default=100000)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--num_epochs", type=float, default=10)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--lr_min", type=float, default=1e-5)
    parser.add_argument("--warmup_ratio", type=float, default=0.1)
    parser.add_argument("--warmfix_ratio", type=float, default=0.9)
    parser.add_argument("--corpus_size", type=str)
    parser.add_argument("--chunk_size", type=int, default=500000)
    parser.add_argument("--vocab_path", type=str, default="data/vocab_32000.txt")
    parser.add_argument("--merges_path", type=str, default="data/merges_32000.txt")
    parser.add_argument("--special_tokens", type=str, nargs="*", default=["<|endoftext|>"])
    parser.add_argument("--log_interval", type=int)
    parser.add_argument("--save_interval", type=int)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--betas", type=float, nargs="*", default=(0.9, 0.95))
    parser.add_argument("--eps", type=float, default=1e-8)
    parser.add_argument("--max_norm", type=float, default=1.0)
    args = parser.parse_args()
    return args